"""ghostshell translator (Mythic PayloadType).

Mythic invokes `build()` when an operator clicks "Create Payload" in the UI.
This reads the base agent + manual_crypto + the selected C2 adapter + the
selected commands, concatenates them into ONE flat Python script (top-level
zero-indent defs/classes), injects the build params as a PARAMS literal, and
returns the script as the payload.

The concatenation strips intra-agent import lines (`from manual_crypto import`,
`from c2... import`, `from . import`) because in the single concatenated script
every name is already in the module globals -- the imports are only needed when
the modules are imported individually for unit tests.
"""

import re
import json
import pathlib
from mythic_container.PayloadBuilder import (
    PayloadType, BuildParameter, BuildParameterType, BuildResponse,
    BuildStatus, BuildStep,
)
from mythic_container.MythicRPC import (
    SendMythicRPCPayloadUpdatebuildStep,
    MythicRPCPayloadUpdateBuildStepMessage,
)

# Lines that reference the agent's own modules -- redundant in the concatenated
# single script (the names are already in globals). Stripped during build.
_STRIP_IMPORT_RE = re.compile(
    r"^\s*from\s+(manual_crypto|c2(?:\.|\s)|\.\s*).*import\b.*$",
    re.MULTILINE,
)


class Ghostshell(PayloadType):
    name = "ghostshell"
    file_extension = "py"
    author = "@ghostshell"
    supported_os = [SupportedOS.Linux, SupportedOS.Windows, SupportedOS.MacOS] if False else None  # set below
    wrapper = False
    wrapped_payloads = []
    mythic_encrypts = True
    note = "A minimal, modular MythicC2 Python payload for teaching tradecraft."
    supports_dynamic_loading = True

    build_parameters = [
        BuildParameter(
            name="python_version",
            parameter_type=BuildParameterType.ChooseOne,
            description="Python version (MVP is Python 3 only).",
            choices=["Python 3"],
            default_value="Python 3",
        ),
    ]

    c2_profiles = ["http", "dynamic_http"]

    agent_path = pathlib.Path(__file__).parent / "mythic"
    agent_code_path = pathlib.Path(__file__).parent / "agent_code"
    agent_icon_path = agent_path / "ghostshell.svg"

    build_steps = [
        BuildStep(step_name="Gathering Files", step_description="Reading base agent + commands + c2 adapter"),
        BuildStep(step_name="Assembling", step_description="Concatenating + injecting params"),
    ]

    translation_container = None

    # supported_os must be a module-level import; set it here to avoid the
    # conditional above (kept simple for readability).
    from mythic_container.MythicCommandBase import SupportedOS
    supported_os = [SupportedOS.Linux, SupportedOS.Windows, SupportedOS.MacOS]

    async def build(self) -> BuildResponse:
        resp = BuildResponse(status=BuildStatus.Success)
        try:
            base_dir = self.agent_code_path
            base_agent_dir = base_dir / "base_agent"

            # 1. Read the foundation files in dependency order.
            crypto_code = (base_agent_dir / "manual_crypto.py").read_text()
            c2_init = (base_agent_dir / "c2" / "__init__.py").read_text()
            c2_http = (base_agent_dir / "c2" / "http.py").read_text()
            c2_dyn = (base_agent_dir / "c2" / "dynamic_http.py").read_text()
            core_code = (base_agent_dir / "core.py").read_text()

            # 2. Read the selected commands (top-level defs).
            command_code = ""
            missing = []
            for cmd in self.commands.get_commands():
                cmd_file = base_dir / "{}.py".format(cmd)
                if cmd_file.exists():
                    command_code += cmd_file.read_text() + "\n"
                else:
                    missing.append(cmd)

            # 3. Concatenate + strip redundant intra-agent imports.
            script = "\n".join([
                "# === ghostshell payload (auto-generated by the translator) ===",
                "# Educational payload -- not for production use.",
                "import os, sys, json, time, random, socket, base64, getpass, platform, threading, subprocess, urllib.request, ssl",
                "",
                "# --- manual_crypto ---",
                crypto_code,
                "",
                "# --- c2 adapter interface ---",
                c2_init,
                "",
                "# --- c2/http ---",
                c2_http,
                "",
                "# --- c2/dynamic_http ---",
                c2_dyn,
                "",
                "# --- base agent core ---",
                core_code,
                "",
                "# --- commands (top-level defs) ---",
                command_code,
                "",
            ])
            script = _STRIP_IMPORT_RE.sub("", script)

            # 4. Inject the build params as a PARAMS literal + the PayloadUUID.
            #    C2 profile params come from self.c2info; the http/dynamic_http
            #    profile defines callback_host, callback_port, AESPSK, etc.
            c2_profile_name = "http"
            c2_params = {}
            for c2 in self.c2info:
                c2_profile_name = c2.get_c2profile()["name"]
                c2_params = c2.get_parameters_dict()
            # Normalize AESPSK (Mythic sends it as a dict with enc_key/dec_key).
            aespsk = c2_params.get("AESPSK", "")
            config = {
                "PayloadUUID": self.uuid,
                "c2_profile": c2_profile_name,
                "AESPSK": aespsk,
            }
            # Merge the rest of the c2 params (callback_host, callback_port, etc.)
            for k, v in c2_params.items():
                if k != "AESPSK":
                    config[k] = v

            params_literal = "PARAMS = " + json.dumps(config, default=str)
            main_block = (
                "\n# === entry point ===\n"
                "if __name__ == \"__main__\":\n"
                "    agent = GhostshellAgent(PARAMS)\n"
                "    agent.run()\n"
            )
            script = script + params_literal + "\n" + main_block

            await SendMythicRPCPayloadUpdatebuildStep(MythicRPCPayloadUpdateBuildStepMessage(
                PayloadUUID=self.uuid,
                StepName="Gathering Files",
                StepStdout="Found base agent + {} commands + {} c2 adapter".format(
                    len(self.commands.get_commands()) - len(missing), c2_profile_name),
                StepSuccess=True,
            ))

            if missing:
                resp.build_stderr = "Missing command files: {}".format(", ".join(missing))

            resp.payload = script.encode()
            resp.build_message = "Built ghostshell payload ({} profile, {} commands).".format(
                c2_profile_name, len(self.commands.get_commands()))
        except Exception as e:
            resp.set_status(BuildStatus.Error)
            resp.build_stderr = "ghostshell build failed: " + str(e)
            resp.build_message = "Build failed"

        await SendMythicRPCPayloadUpdatebuildStep(MythicRPCPayloadUpdateBuildStepMessage(
            PayloadUUID=self.uuid,
            StepName="Assembling",
            StepStdout="Payload assembled ({} bytes)".format(len(resp.payload) if resp.payload else 0),
            StepSuccess=(resp.status == BuildStatus.Success),
        ))
        return resp
